### ISSUE TITLE
Fix dependencies when not doing a public release

### ISSUE THREAD

**Issue by provirus** [foilen/foilen-infra-plugins-core#25]
12:06:49.602 [Timer/executeLater] INFO  c.f.i.r.l.plugin.LetsencryptHelper - Will update certificates: [test-websocket.foilen-lab.com]
12:06:49.608 [Timer/executeLater] ERROR c.f.i.u.p.TimerExecutionRunnable - Problem executing the timer
java.lang.NoClassDefFoundError: org/shredzone/acme4j/exception/AcmeException
        at com.foilen.infra.resource.letsencrypt.plugin.LetsencryptHelper.createChallengesAndCreateTimer(LetsencryptHelper.java:78)
        at com.foilen.infra.resource.letsencrypt.plugin.LetsEncryptWebsiteCertificateEditor.lambda$fillResource$0(LetsEncryptWebsiteCertificateEditor.java:78)
        at com.foilen.infra.ui.plugin.TimerExecutionRunnable.run(TimerExecutionRunnable.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.shredzone.acme4j.exception.AcmeException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 common frames omitted

**Comment by provirus** [comment]
This is only happening when not creating a public build
